name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'include'
          - 'tests'
          - 'examples'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.17.0
        with:
          check-path: ${{ matrix.path }}
